#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

npm run fix
npm run test

if [ -d "./template-test" ]; then
  pushd template-test
  npm run format
  npm run test
  node ./bin/run.js hello --name world

  npm pkg get dependencies > ../templates/dependencies.json
  npm pkg get devDependencies > ../templates/dev-dependencies.json
  popd
fi

npm version patch --no-git-tag-version
