name: upgrade-node-dependencies

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate-test-project-from-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: "lts/*"
          check-latest: true
      - name: Generate a test project
        shell: bash
        run: |
          set -euo pipefail

          npm install
          rm -rf template-test
          node ./bin/run.js generate -I --directory-name template-test --package-name template-test --command-name template-test
      - uses: fardjad/my-actions/npm-automatic-dependency-update@main
        with:
          github-token: ${{ secrets.GH_PAT }}
          ncu-check-extra-flags: --deep -x eslint
          ncu-upgrade-extra-flags: --deep -x eslint
          dependency-install-script: scripts/install-dependencies
          post-upgrade-hook-script: scripts/post-upgrade-hook
          commit-message-preprocessor-script: scripts/commit-message-preprocessor.mjs
